@echo off 

PapyrusCompiler SKI_ActiveEffectsWidget.psc -i=".\lib\jcontainer\source;.\lib\skyui\source;.\lib\immersiveVoice\source;.\lib\po3\source;.\lib\racemenu\source;.\lib\creature\source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\Scripts\Source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts;" -o="c:\Games\ModOrganizer\SkyrimSE\overwrite\scripts" -f="D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts\TESV_Papyrus_Flags.flg"
PapyrusCompiler SKI_ConfigBase.psc -i=".\lib\jcontainer\source;.\lib\skyui\source;.\lib\immersiveVoice\source;.\lib\po3\source;.\lib\racemenu\source;.\lib\creature\source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\Scripts\Source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts;" -o="c:\Games\ModOrganizer\SkyrimSE\overwrite\scripts" -f="D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts\TESV_Papyrus_Flags.flg"
PapyrusCompiler SKI_ConfigManager.psc -i=".\lib\jcontainer\source;.\lib\skyui\source;.\lib\immersiveVoice\source;.\lib\po3\source;.\lib\racemenu\source;.\lib\creature\source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\Scripts\Source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts;" -o="c:\Games\ModOrganizer\SkyrimSE\overwrite\scripts" -f="D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts\TESV_Papyrus_Flags.flg"
PapyrusCompiler SKI_ConfigMenu.psc -i=".\lib\jcontainer\source;.\lib\skyui\source;.\lib\immersiveVoice\source;.\lib\po3\source;.\lib\racemenu\source;.\lib\creature\source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\Scripts\Source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts;" -o="c:\Games\ModOrganizer\SkyrimSE\overwrite\scripts" -f="D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts\TESV_Papyrus_Flags.flg"
PapyrusCompiler SKI_FavoritesManager.psc -i=".\lib\jcontainer\source;.\lib\skyui\source;.\lib\immersiveVoice\source;.\lib\po3\source;.\lib\racemenu\source;.\lib\creature\source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\Scripts\Source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts;" -o="c:\Games\ModOrganizer\SkyrimSE\overwrite\scripts" -f="D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts\TESV_Papyrus_Flags.flg"
PapyrusCompiler SKI_Main.psc -i=".\lib\jcontainer\source;.\lib\skyui\source;.\lib\immersiveVoice\source;.\lib\po3\source;.\lib\racemenu\source;.\lib\creature\source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\Scripts\Source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts;" -o="c:\Games\ModOrganizer\SkyrimSE\overwrite\scripts" -f="D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts\TESV_Papyrus_Flags.flg"
PapyrusCompiler SKI_PlayerLoadGameAlias.psc -i=".\lib\jcontainer\source;.\lib\skyui\source;.\lib\immersiveVoice\source;.\lib\po3\source;.\lib\racemenu\source;.\lib\creature\source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\Scripts\Source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts;" -o="c:\Games\ModOrganizer\SkyrimSE\overwrite\scripts" -f="D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts\TESV_Papyrus_Flags.flg"
PapyrusCompiler SKI_QF_ConfigManagerInstance.psc -i=".\lib\jcontainer\source;.\lib\skyui\source;.\lib\immersiveVoice\source;.\lib\po3\source;.\lib\racemenu\source;.\lib\creature\source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\Scripts\Source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts;" -o="c:\Games\ModOrganizer\SkyrimSE\overwrite\scripts" -f="D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts\TESV_Papyrus_Flags.flg"
PapyrusCompiler SKI_QuestBase.psc -i=".\lib\jcontainer\source;.\lib\skyui\source;.\lib\immersiveVoice\source;.\lib\po3\source;.\lib\racemenu\source;.\lib\creature\source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\Scripts\Source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts;" -o="c:\Games\ModOrganizer\SkyrimSE\overwrite\scripts" -f="D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts\TESV_Papyrus_Flags.flg"
PapyrusCompiler SKI_SettingsManager.psc -i=".\lib\jcontainer\source;.\lib\skyui\source;.\lib\immersiveVoice\source;.\lib\po3\source;.\lib\racemenu\source;.\lib\creature\source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\Scripts\Source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts;" -o="c:\Games\ModOrganizer\SkyrimSE\overwrite\scripts" -f="D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts\TESV_Papyrus_Flags.flg"

PapyrusCompiler SKI_WidgetBase.psc -i=".\lib\jcontainer\source;.\lib\skyui\source;.\lib\immersiveVoice\source;.\lib\po3\source;.\lib\racemenu\source;.\lib\creature\source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\Scripts\Source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts;" -o="c:\Games\ModOrganizer\SkyrimSE\overwrite\scripts" -f="D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts\TESV_Papyrus_Flags.flg"
PapyrusCompiler SKI_WidgetManager.psc -i=".\lib\jcontainer\source;.\lib\skyui\source;.\lib\immersiveVoice\source;.\lib\po3\source;.\lib\racemenu\source;.\lib\creature\source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\Scripts\Source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts;" -o="c:\Games\ModOrganizer\SkyrimSE\overwrite\scripts" -f="D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts\TESV_Papyrus_Flags.flg"

