@echo off 

PapyrusCompiler ImmersivePcVoiceActionQuest.psc -i=".\lib\immersiveVoice\source;.\lib\po3\source;.\lib\racemenu\source;.\lib\creature\source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\Scripts\Source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts;" -o="D:\Games\ModOrganizer\SkyrimSE\overwrite\scripts" -f="D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts\TESV_Papyrus_Flags.flg"
PapyrusCompiler ImmersivePcVoiceActionActorAlias.psc -i=".\lib\immersiveVoice\source;.\lib\po3\source;.\lib\racemenu\source;.\lib\creature\source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\Scripts\Source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts;" -o="D:\Games\ModOrganizer\SkyrimSE\overwrite\scripts" -f="D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts\TESV_Papyrus_Flags.flg"

PapyrusCompiler ImmersivePcVoiceCombatQuest.psc -i=".\lib\immersiveVoice\source;.\lib\po3\source;.\lib\racemenu\source;.\lib\creature\source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\Scripts\Source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts;" -o="D:\Games\ModOrganizer\SkyrimSE\overwrite\scripts" -f="D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts\TESV_Papyrus_Flags.flg"
PapyrusCompiler ImmersivePcVoiceCombatActorAlias.psc -i=".\lib\immersiveVoice\source;.\lib\po3\source;.\lib\racemenu\source;.\lib\creature\source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\Scripts\Source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts;" -o="D:\Games\ModOrganizer\SkyrimSE\overwrite\scripts" -f="D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts\TESV_Papyrus_Flags.flg"

PapyrusCompiler ImmersivePcVoiceMonologueQuest.psc -i=".\lib\immersiveVoice\source;.\lib\po3\source;.\lib\racemenu\source;.\lib\creature\source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\Scripts\Source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts;" -o="D:\Games\ModOrganizer\SkyrimSE\overwrite\scripts" -f="D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts\TESV_Papyrus_Flags.flg"
PapyrusCompiler ImmersivePcVoiceMonologueActorAlias.psc -i=".\lib\immersiveVoice\source;.\lib\po3\source;.\lib\racemenu\source;.\lib\creature\source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\Scripts\Source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts;" -o="D:\Games\ModOrganizer\SkyrimSE\overwrite\scripts" -f="D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts\TESV_Papyrus_Flags.flg"

PapyrusCompiler ImmersivePcVoiceStatusQuest.psc -i=".\lib\immersiveVoice\source;.\lib\po3\source;.\lib\racemenu\source;.\lib\creature\source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\Scripts\Source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts;" -o="D:\Games\ModOrganizer\SkyrimSE\overwrite\scripts" -f="D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts\TESV_Papyrus_Flags.flg"
PapyrusCompiler ImmersivePcVoiceStatusActorAlias.psc -i=".\lib\immersiveVoice\source;.\lib\po3\source;.\lib\racemenu\source;.\lib\creature\source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\Scripts\Source; D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts;" -o="D:\Games\ModOrganizer\SkyrimSE\overwrite\scripts" -f="D:\Games\The Elder Scrolls - Skyrim - Special Edition\Data\source\scripts\TESV_Papyrus_Flags.flg"
